[package]
name = "problemdetails"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "Support for Problem Details (RFC-7807 / RFC-9457) responses in HTTP APIs"
homepage = "https://github.com/sazzer/problemdetails/"
repository = "https://github.com/sazzer/problemdetails/"
readme = "README.md"
keywords = ["rfc-7807", "rfc-8457", "http", "problemdetails"]
categories = ["web-programming::http-server", "api-bindings"]

[dependencies]
axum = { version = "0.7.1", optional = true }
tower-http = { version = "0.5.0", features = ["catch-panic"], optional = true }
http = "1.0.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108", features = ["preserve_order"] }

[dev-dependencies]
assert2 = "0.3.11"
axum-test = "14.0.0-rc.1"
hyper = { version = "1.0.1", features = ["full"] }
insta = { version = "1.34.0", features = ["json"] }
tokio = { version = "1.34.0", features = ["full"] }

[features]
axum = ["dep:axum", "dep:tower-http"]
