[package]
name = "problemdetails"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Support for Problem Details (RFC-7807) responses in HTTP APIs"
homepage = "https://github.com/sazzer/problemdetails/"
repository = "https://github.com/sazzer/problemdetails/"
readme = "README.md"
keywords = ["rfc-7807", "http", "problemdetails"]
categories = ["web-programming::http-server", "api-bindings"]

[dependencies]
axum = { version = "0.6.1", optional = true}
http = "0.2.8"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = { version = "1.0.89", features = ["preserve_order"] }

[dev-dependencies]
assert2 = "0.3.7"
hyper = { version = "0.14.23", features = ["full"] }
insta = { version = "1.21.2", features = ["json"] }
tokio = { version = "1.22.0", features = ["full"] }

[features]
axum = ["dep:axum"]
